rtabmap:
  ros__parameters:
    frame_id: reconrobot/base_link
    odom_frame_id: world
    map_frame_id: map
    wait_for_transform: 0.5
    subscribe_depth: false
    subscribe_rgb: false
    subscribe_scan: false
    subscribe_scan_cloud: true
    subscribe_odom_info: false
    cloud_min_z: -50.0      # minimum z to keep
    cloud_max_z:  1.0       # maximum z — cuts water surface
    cloud_voxel_size: 0.1   # voxel downsample
    approx_sync: true
    topic_queue_size: 30
    sync_queue_size: 30
    qos_odom: 1
    qos_scan_cloud: 1
    Reg/Strategy: "1"
    Grid/FromDepth: "false"
    Grid/CellSize: "0.1"
    Grid/MinClusterSize: "10"     # remove isolated points
    Grid/MaxObstacleHeight: "1.0" # max obstacle height from ground
    Grid/RayTracing: "true"       # better free space estimation
    ICP/VoxelSize: "0.1"
    ICP/MaxCorrespondenceDistance: "2.0"
    ICP/Iterations: "30"
    ICP/PointToPlane: "false"
    Mem/IncrementalMemory: "true"
    RGBD/AngularUpdate: "0.1"
    RGBD/LinearUpdate: "0.1"

rtabmap_viz:                      
  ros__parameters:
    frame_id: reconrobot/base_link
    odom_frame_id: world
    subscribe_depth: false
    subscribe_rgb: false
    subscribe_scan: false
    subscribe_scan_cloud: true
    subscribe_odom_info: false
    approx_sync: true
    topic_queue_size: 30
    sync_queue_size: 30
    qos_odom: 1
    qos_scan_cloud: 1 